repository-url: ""
authenticate: "false"
token: ""
not-authenticated: "&3&lServer >> &4&lAuthentication is disabled at the moment!"
webhook-port: "7123"
busy: "&3&lServer >> &4&lCurrently busy!"
permission-denied: "&3&lServer >> &7No Permission"
outdated-commit: "&3&lServer >> &4&lThis Commit is outdated or has been accepted already"
invalid-commit: "&3&lServer >> &4&lInvalid Commit"
successful-commit: "&3&lServer >> &a&lSuccessfully merged Commits"
successful-plugin: "&3&lServer >> &a&lSuccessfully upgraded plugin Resources"
missing-argument: "&3&lServer >> &4&lMissing argument for <Commit COMPARE / Plugin NAME / Path DIRECTORY>"
invalid-plugin: "&3&lServer >> &4&lInvalid plugin. Check your spelling. /plugins"
invalid-directory: "&3&lServer >> &4&lInvalid directory. Check your spelling. Must start with /"
muted: "&3&lServer >> &7Notifications have been %status%"
commit-header: "&4&l========= Commit detected ========="
commit-name: "&4&lPusher : %name%"
commit-message: "&4&lMessage: %message%"
commit-changes: "&4&lChanges: [LINK]"
commit-changes-hover: "&4&l%link%"
commit-accept: "&4&lAccept this commit? [CLICK HERE]"
commit-accept-hover: "&4&lOnly click this message if you are ABSOLUTELY SURE you want to merge the files"
commit-auto: "&4&lAutomatic action performed: &c%command%"
commit-footer: "&4&l==================================="
reload-format: "&4[&c%plugin%&4]"
reload-hover: "&4&lClick here to reload Plugin: &c%plugin%"
export-successful: "&3&lServer >> &7Successfully exported"
export-message: "Automatic export by %player%: %path%"
export-contains: "Automatic export by"
clean-successful: "&3&lServer >> &a&lSuccessfully deleted all local cache files"
compare-jar: "true"
compare-other: "false"
whitelist-filetypes: "true"
filetypes:
  - ".yml"
  - ".txt"
  - ".json"
  - ".properties"
  - ".png"
  - ".jar"
op-pushers:
  - "Konstanius"
