name: GitMcSync
version: 'R-1.5'
main: konstanius.gitmcsync.GitMcSync
api-version: 1.17
load: STARTUP
depend: [ BileTools ]
authors: [ konstanius ]
commands:
  gitmerge:
    description: "gitsync.merge"
  gitpull:
    description: "gitsync.merge"
  gitupgrade:
    description: "gitsync.merge"
  gitmute:
    description: "gitsync.mute"
  gitexport:
    description: "gitsync.export"
  gitclean:
    description: "gitsync.clean"